### ISSUE TITLE
Fix Xcode 8 / iOS 10 Requirement

### ISSUE THREAD

**Issue by jhickmanEB** [BeauNouvelle/AspectFillFaceAware#2]
I wanted to test your library out to see if it would work for an app I am developing, but it looks like you built the entire example app in Xcode 8 Beta using iOS 10. You really shouldn't release public libraries under Betas. Would love to see this re-built in the current release version of Xcode.

Cheers!

**Comment by BeauNouvelle** [comment]
There's a Swift 2.3 version bundled in there too. 
However, the example project only runs on Swift 3 and Xcode 8.

Just drag the 2.3 file in to your project and test it out that way. Let me know if you have any problems with it!
