### ISSUE TITLE
Use of unresolved identifier 'DispatchQueue'

### ISSUE THREAD

**Issue by unittesting0** [BeauNouvelle/AspectFillFaceAware#4]
Just downloaded the example and I'm not able to run it on my phone!

"Use of unresolved identifier 'DispatchQueue'"

Am I missing anything?

**Comment by unittesting0** [comment]
Never mind I had to delete the swift3 file, then edit the source code of Main.storyboard and LaunchScreen.storyboard to run on Xcode 7.

**Comment by BeauNouvelle** [comment]
I'm glad you were able to work it out.
